config/routes.rb
Rails.application.routes.draw do
  resources :crews
  resources :genres
  resources :dashboard
  resources :movies

   root 'dashboard#index'

end

app/models/crew.rb
class Crew < ActiveRecord::Base
  has_many :roles
  has_many :movies, through: :roles
end

app/models/genre.rb
class Genre < ActiveRecord::Base

end

app/models/movie.rb
require 'elasticsearch/model'
class Movie < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :roles
  has_many :crews, through: :roles

  mapping do
    indexes :id, index: :not_analyzed
    indexes :name
    indexes :synopsis
    indexes :year
    indexes :language
    indexes :country
    indexes :runtime,  type: 'integer'
    indexes :review,   type: 'float'
  end

  def as_indexed_json(options = {})
    self.as_json(only: [:id, :name, :synopsis, :year, :country, :language, :runtime, :review],
      include: {
      crews:  { only: [:id, :name] },
      roles: { only: [:id, :job] }
    })
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :movie
  belongs_to :crew
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: [:show, :edit, :update, :destroy]

  # GET /crews
  # GET /crews.json
  def index
    @crews = Crew.order(:name).page params[:page]
  end

  # GET /crews/1
  # GET /crews/1.json
  def show
  end

  # GET /crews/new
  def new
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
  end

  # POST /crews
  # POST /crews.json
  def create
    @crew = Crew.new(crew_params)

    respond_to do |format|
      if @crew.save
        format.html { redirect_to @crew, notice: 'Crew was successfully created.' }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1
  # PATCH/PUT /crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to @crew, notice: 'Crew was successfully updated.' }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1
  # DELETE /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to crews_url, notice: 'Crew was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crew_params
      params.require(:crew).permit(:name)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index

  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.order(:name).page params[:page]
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.__elasticsearch__.search(params[:search].present? ? search_params['name'] : '*').results
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def movie_params
    params.require(:movie).permit(:name, :synopsis, :country, :year, :review, :rating, :runtime, :language, :release_date)
  end

  def search_params
    params.require(:search).permit(:name) if params[:search]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/crews/_form.html.erb
<%= form_for(@crew) do |f| %>
  <% if @crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% @crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form' %>

<%= link_to 'Show', @crew %> |
<%= link_to 'Back', crews_path %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Crews</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= link_to 'Show', crew %></td>
        <td><%= link_to 'Edit', edit_crew_path(crew) %></td>
        <td><%= link_to 'Destroy', crew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @crews %>
<br>

<%= link_to 'New Crew', new_crew_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form' %>

<%= link_to 'Back', crews_path %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crew.name %>
</p>

<%= link_to 'Edit', edit_crew_path(@crew) %> |
<%= link_to 'Back', crews_path %>

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Genres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @genres %>
<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Movies Search" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="row">
<div class="large-2 columns"></div>
<div class="large-10 columns"><%= yield %></div>
<div class="large-2 columns"></div>
</div>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_field :review %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :runtime %><br>
    <%= f.number_field :runtime %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.date_select :release_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_search.html.erb
<%= form_tag(movies_path,  method: "get", class: "form") do %>
    <div class="row">
      <input type="text" name="search[name]" placeholder="Search the movies">
      <%= submit_tag("Search", class: "button tiny") %>
    </div>
  <% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'search' %>

<h1>Listing Movies</h1>

    <% @movies.each do |movie| %>
    <div class="panel">
      <h4><%= movie.name %></h4>
       <%= movie.synopsis %>
       <hr>
       <h4>Crews</h4>
       <% movie.crews.each do |crew|%>
         <span class="label"><%= crew.name %></span>
       <% end %>
       <hr>
      <h4>Roles</h4>
       <% movie.roles.each do |role|%>
         <span class="label"><%= role.job %></span>
       <% end %>
    </div>
    <% end %>
<%= paginate @movies %>
<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Country:</strong>
  <%= @movie.country %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Review:</strong>
  <%= @movie.review %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @movie.runtime %>
</p>

<p>
  <strong>Language:</strong>
  <%= @movie.language %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>